name: Static Scans # display name

on:
  #push: # not on push for the training (just manual)
  workflow_dispatch: # to allow running manually

permissions: # overwrites default permissions
  contents: read

jobs:
  sast-scans: # any valid key used as id
    name: SAST Scans # display name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4 # references an action (defines the code to run this step)
        with: # specifies paramters of the action used
          persist-credentials: false # should keep github read-token for following steps and actions?

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "temurin"

      - name: Setup Maven Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install
